language: python
dist: xenial
python:
  # - "3.4"
  # - "3.5"
  # - "3.6"      # current default Python on Travis CI
  - "3.7"
  # - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
# command to run tests
script:
  - pytest --cov=routely/
after_success:
  - coveralls
